### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by Weefle** [BurnyDaKath/OMGPI#5]
I get an error on server load: https://hastebin.com/emagebofoc.bash
My main.omgc file: https://hastebin.com/ikiyabasul.pl
My database works perfectly with other plugins!
I did all you said here: http://omgpi.tk/docs/

**Comment by BurnyDaKath** [comment]
Interested in version you are running OMGPI on. There was a change specific to one library (org.bukkit.craftbukkit.libs.joptsimple.internal.Strings) in 1.12, i will have to put it in OMGPI itself if that is the case.

**Comment by BurnyDaKath** [comment]
Ignore the question, i notice that your version is 1.9.x with further inspection of the code. I will fix this shortly.

**Comment by BurnyDaKath** [comment]
Check 1.0.1 if that may fix your problem and close issue if it did.

**Comment by Weefle** [comment]
Database works good now.
But the problems with your plugin are:
- this error on first load if there aren't any plugins: https://hastebin.com/ajucohibiv.bash (just add an error message like "there is no plugins yet")
- I must create myself the /games directory (an auto-create may be good)
- the main.omgc file is displayed like that: https://hastebin.com/jofadeduro.diff at the first start
- I must create myself the /maps/mapname/map.omgc directory and file and I got this error: https://hastebin.com/urayenaqal.md and my map.omgc file is auto-filed with that: https://hastebin.com/nikumubido.diff
I think that's all for now :D
Sorry for my bad english :/

**Comment by BurnyDaKath** [comment]
Always ready to help. Will look into all possible bugs and fix them.

**Comment by Weefle** [comment]
Ok, thank you, your plugin will be awesome! :D

**Comment by BurnyDaKath** [comment]
There was no problem with map.omgc. The plugin did not add optional settings to mapfig, which are shown in the docs. Make sure you setup your map for your game properly. The errors were unrelated, but i will fix those anyway. (They were about kitfigs)

The table is infact simply not required. The Docs state, that game creator that makes games for OMGPI should tell how to create a table, or give file to import the table into your database.

Check release 1.0.2 to see if errors disappear.

**Comment by BurnyDaKath** [comment]
If plugin did not fix those errors, add displayItem: '{id:stone,Count:1,tag:{display:{Name:"Default"}}}' to Default.kit on your own.

**Comment by Weefle** [comment]
Do you have skype?
If you have, add me: live:benoit.db2000
I have some errors that I need to be explained.
I could show you my problems on screen sharing.

**Comment by BurnyDaKath** [comment]
Please use GitHub issues or SpigotMC OMGPI discussion to report bugs and issues.

**Comment by Weefle** [comment]
Your plugin works good now but can you add an auto-create to /maps/defaultmap/map.omgc directory because I get this error: https://hastebin.com/xeviluwusa.css
I get this error when a mob shoot to me in skywars waiting area: https://hastebin.com/yiyuziyibu.bash
I get this error: https://hastebin.com/rofewomupa.md when I tested your Map setup here: http://omgpi.tk/docs/mapfig (column problem probably due to the website)
Why I get a null pointer here?: https://hastebin.com/leqatoteta.md ("Loading game null...")
And after tested your sjywars plugin, when I killed the last people, the game didn't stop, I used this in game.omgc: https://hastebin.com/wevaziyagi.bash and this in map.omgc: https://hastebin.com/taxisopedu.diff but I left the Default.kit empty.

**Comment by BurnyDaKath** [comment]
"Loading game null..." is a normal behaviour of OMGPI, meaning it loads random game instead of pre-set one.

YAML error caused by wrong formatting, use [YAML Online parser](http://yaml-online-parser.appspot.com/). Problem there caused by colon in a string, do something like - '{stuffhere}'.

Notice the mapfig given in docs is not a proper mapfig: you have to create one yourself. That only shows an example with values that would probably cause errors.

Mob shooting must be fixed in 1.0.3. I would recommend having mob spawning in prelobby (waiting area, as you've called it).

The problem with game not stopping might be due to game not even starting because of the errors of the mapfig. Docs also say that in installation you should create all maps folders yourself.

**Comment by Weefle** [comment]
The game can't stop (I don't know why, I used this config with no error: https://hastebin.com/numireqami.php) and the coins are not saved (no tables in database), maybe because the game don't stop? I don't know.
And the teleportation at the start is so long, the second player is teleported more later that the first.
And please remove the error on console when there isn't map configured: https://hastebin.com/hinaxodazo.css
I get this error, like the shoot before but for the damage: https://hastebin.com/agifuqoyuy.bash

**Comment by BurnyDaKath** [comment]
Coins are not supposed to be saved, those are Game Coins meaning they appear only for that game.

All fixed in 1.0.4, except for the problems with mapfig - you got to setup your maps.

**Comment by Weefle** [comment]
Ok all works now good but the start takes always a lot of time.
I don't know how to use kits.
And the rightclick is always buggy, please make it functional in air.

**Comment by BurnyDaKath** [comment]
http://omgpi.tk/docs/kits

Right click does not need clicking on blocks.

Starting time is long probably due to your server setup. It works alright on my PC and remote server.

**Comment by Weefle** [comment]
But you said "Right click any block to open "/options" menu." and when I rightclick on air, nothing happen.

**Comment by BurnyDaKath** [comment]
Sorry typo, Right click does not need clicking on air now because the inventory is too simple and clicking on air is not that necessary of a feature.

**Comment by Weefle** [comment]
Ok all works fine, I think for the new users, you could add that in Default.kit: https://hastebin.com/ebixulijog.pl and create automatically the /maps directory.
I get this error at the aend of the party: https://hastebin.com/pihejorofi.md
And why am I teleported to the prelobby? Can I be teleported to the hub server with bungeecord for example?
And the game start takes not a lot of time, it's the teleportation between players

**Comment by BurnyDaKath** [comment]
Errors appear due to how minecraft world system is made. If there was no world session locking (which i would never understand why it was added) the errors would not appear.

OMGPI is highly customizable - it is open source, meaning any OMGPI user can change OMGPI source code for their liking and have custom one on their server. The teleportation to prelobby is done similarly to servers like Mineplex.

**Comment by Weefle** [comment]
Important questions:
And the game start takes not a lot of time, it's the teleportation between players
And also, how can I do chest refill for the skywars?
And what is the database for? I want the coins can be saved.

**Comment by BurnyDaKath** [comment]
For saving coins, you have to have custom games .jars you might code or ask a developer to do. 

http://omgpi.tk/docs/loots - chest refilling.

I dont have problem with teleportation between players, as i said, your system might be underpowered.

**Comment by Weefle** [comment]
Ok I now the problem for teleportation, it's my server sorry.
Can you just add a message after a player choosed a kit? there isn't message.

**Comment by BurnyDaKath** [comment]
I'll fix GUIs problems tomorrow - only selected items supposed to glow

**Comment by Weefle** [comment]
Ok good, thank you! :D
